/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.Cliente;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class Bingo extends javax.swing.JFrame {

    /**
     * Creates new form Bingo
     */
    Cliente cliente;
    
    public Bingo(Cliente cliente) {
        this.cliente = cliente;
        initComponents();
    }

     public Bingo() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        bB1 = new javax.swing.JButton();
        bB2 = new javax.swing.JButton();
        bB3 = new javax.swing.JButton();
        bB4 = new javax.swing.JButton();
        bB5 = new javax.swing.JButton();
        bI1 = new javax.swing.JButton();
        bI2 = new javax.swing.JButton();
        bI3 = new javax.swing.JButton();
        bI4 = new javax.swing.JButton();
        bI5 = new javax.swing.JButton();
        bN1 = new javax.swing.JButton();
        bN2 = new javax.swing.JButton();
        bN3 = new javax.swing.JButton();
        bN4 = new javax.swing.JButton();
        bN5 = new javax.swing.JButton();
        bG1 = new javax.swing.JButton();
        bG2 = new javax.swing.JButton();
        bG3 = new javax.swing.JButton();
        bG4 = new javax.swing.JButton();
        bG5 = new javax.swing.JButton();
        bO1 = new javax.swing.JButton();
        bO2 = new javax.swing.JButton();
        bO3 = new javax.swing.JButton();
        bO4 = new javax.swing.JButton();
        bO5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lNumero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lTempo = new javax.swing.JLabel();
        bingo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        bB1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bB1ActionPerformed(evt);
            }
        });

        bB2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bB2ActionPerformed(evt);
            }
        });

        bB3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bB3ActionPerformed(evt);
            }
        });

        bB4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bB4ActionPerformed(evt);
            }
        });

        bB5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bB5ActionPerformed(evt);
            }
        });

        bI1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bI1ActionPerformed(evt);
            }
        });

        bI2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bI2ActionPerformed(evt);
            }
        });

        bI3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bI3ActionPerformed(evt);
            }
        });

        bI4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bI4ActionPerformed(evt);
            }
        });

        bI5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bI5ActionPerformed(evt);
            }
        });

        bN1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN1ActionPerformed(evt);
            }
        });

        bN2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN2ActionPerformed(evt);
            }
        });

        bN3.setFont(new java.awt.Font("Arial Black", 0, 8)); // NOI18N
        bN3.setText("FREE");
        bN3.setEnabled(false);

        bN4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN4ActionPerformed(evt);
            }
        });

        bN5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bN5ActionPerformed(evt);
            }
        });

        bG1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bG1ActionPerformed(evt);
            }
        });

        bG2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bG2ActionPerformed(evt);
            }
        });

        bG3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bG3ActionPerformed(evt);
            }
        });

        bG4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bG4ActionPerformed(evt);
            }
        });

        bG5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bG5ActionPerformed(evt);
            }
        });

        bO1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bO1ActionPerformed(evt);
            }
        });

        bO2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bO2ActionPerformed(evt);
            }
        });

        bO3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bO3ActionPerformed(evt);
            }
        });

        bO4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bO4ActionPerformed(evt);
            }
        });

        bO5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bO5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bO5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("B");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText("N");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("G");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setText("O");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("I");

        lNumero.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Número");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Tempo");

        lTempo.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lTempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bingo.setBackground(new java.awt.Color(0, 255, 0));
        bingo.setText("BINGO!");
        bingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bingoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btnSair)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bB1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bI1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bN1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bG1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bO1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bB4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bI4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bN4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bG4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bO4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bB5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bI5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bN5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bG5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bO5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bB2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bI2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bN2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bG2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bO2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bB3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bI3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bN3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bG3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bO3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bingo)
                                        .addContainerGap())))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bB1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bI1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bN1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bG1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bO1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bB2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bI2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bN2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bG2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bO2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bB3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(bG3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(bO3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(bN3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(bI3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bB4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bN4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bO4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bB5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bI5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bN5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bG5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bO5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(bingo)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        try {
            this.cliente.desabilitarJogo();
            JOptionPane.showMessageDialog(rootPane, "O cliente foi desabilitado!", "Desabilitar Cliente", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
        } catch (IOException ex) {
            //Logger.getLogger(SalaEspera.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Sair");
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void bG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bG1ActionPerformed
        // TODO add your handling code here:
        bG1.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bG1.getText())));
        
    }//GEN-LAST:event_bG1ActionPerformed

    private void bG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bG2ActionPerformed
        // TODO add your handling code here:
        bG2.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bG2.getText())));
        
    }//GEN-LAST:event_bG2ActionPerformed

    private void bG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bG3ActionPerformed
        // TODO add your handling code here:
        bG3.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bG3.getText())));
        
    }//GEN-LAST:event_bG3ActionPerformed

    private void bG4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bG4ActionPerformed
        // TODO add your handling code here:
        bG4.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bG4.getText())));
        
    }//GEN-LAST:event_bG4ActionPerformed

    private void bG5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bG5ActionPerformed
        // TODO add your handling code here:
        bG5.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bG5.getText())));
        
    }//GEN-LAST:event_bG5ActionPerformed

    private void bO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bO1ActionPerformed
        // TODO add your handling code here:
        bO1.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bO1.getText())));
        
    }//GEN-LAST:event_bO1ActionPerformed

    private void bO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bO2ActionPerformed
        // TODO add your handling code here:
        bO2.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bO2.getText())));
        
    }//GEN-LAST:event_bO2ActionPerformed

    private void bO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bO3ActionPerformed
        // TODO add your handling code here:
        bO3.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bO3.getText())));
        
    }//GEN-LAST:event_bO3ActionPerformed

    private void bO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bO4ActionPerformed
        // TODO add your handling code here:
        bO4.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bO4.getText())));
        //System.out.println("Número " + Integer.parseInt(bO4.getText()));
        
    }//GEN-LAST:event_bO4ActionPerformed

    private void bO5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bO5ActionPerformed
        // TODO add your handling code here:
        bO5.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bO5.getText())));
        
    }//GEN-LAST:event_bO5ActionPerformed

    private void bB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bB1ActionPerformed
        bB1.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bB1.getText())));
        
    }//GEN-LAST:event_bB1ActionPerformed

    private void bI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bI1ActionPerformed
        bI1.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bI1.getText())));
        
    }//GEN-LAST:event_bI1ActionPerformed

    private void bB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bB2ActionPerformed
        bB2.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bB2.getText())));        // TODO add your handling code here:
    }//GEN-LAST:event_bB2ActionPerformed

    private void bB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bB3ActionPerformed
        // TODO add your handling code here:
        bB3.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bB3.getText())));
        
    }//GEN-LAST:event_bB3ActionPerformed

    private void bB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bB4ActionPerformed
        // TODO add your handling code here:
        bB4.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bB4.getText())));
        
    }//GEN-LAST:event_bB4ActionPerformed

    private void bB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bB5ActionPerformed
        // TODO add your handling code here:
        bB5.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bB5.getText())));
        
    }//GEN-LAST:event_bB5ActionPerformed

    private void bI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bI2ActionPerformed
        // TODO add your handling code here:
        bI2.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bI2.getText())));
        
    }//GEN-LAST:event_bI2ActionPerformed

    private void bI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bI3ActionPerformed
        // TODO add your handling code here:
        bI3.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bI3.getText())));
        
    }//GEN-LAST:event_bI3ActionPerformed

    private void bI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bI4ActionPerformed
        // TODO add your handling code here:
        bI4.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bI4.getText())));
        
    }//GEN-LAST:event_bI4ActionPerformed

    private void bI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bI5ActionPerformed
        // TODO add your handling code here:
        bI5.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bI5.getText())));
        
    }//GEN-LAST:event_bI5ActionPerformed

    private void bN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN1ActionPerformed
        // TODO add your handling code here
        bN1.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bN1.getText())));
        
    }//GEN-LAST:event_bN1ActionPerformed

    private void bN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN2ActionPerformed
        // TODO add your handling code here:
        bN2.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bN2.getText())));
        
    }//GEN-LAST:event_bN2ActionPerformed

    private void bN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN4ActionPerformed
        // TODO add your handling code here:
        bN4.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bN4.getText())));
        
    }//GEN-LAST:event_bN4ActionPerformed

    private void bN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bN5ActionPerformed
        // TODO add your handling code here:
        bN5.setEnabled(this.cliente.marcarNumero(Integer.parseInt(bN5.getText())));
        
    }//GEN-LAST:event_bN5ActionPerformed

    private void bingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bingoActionPerformed
        this.cliente.gritarBingo();
    }//GEN-LAST:event_bingoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bingo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bB1;
    public javax.swing.JButton bB2;
    public javax.swing.JButton bB3;
    public javax.swing.JButton bB4;
    public javax.swing.JButton bB5;
    public javax.swing.JButton bG1;
    public javax.swing.JButton bG2;
    public javax.swing.JButton bG3;
    public javax.swing.JButton bG4;
    public javax.swing.JButton bG5;
    public javax.swing.JButton bI1;
    public javax.swing.JButton bI2;
    public javax.swing.JButton bI3;
    public javax.swing.JButton bI4;
    public javax.swing.JButton bI5;
    public javax.swing.JButton bN1;
    public javax.swing.JButton bN2;
    public javax.swing.JButton bN3;
    public javax.swing.JButton bN4;
    public javax.swing.JButton bN5;
    public javax.swing.JButton bO1;
    public javax.swing.JButton bO2;
    public javax.swing.JButton bO3;
    public javax.swing.JButton bO4;
    public javax.swing.JButton bO5;
    private javax.swing.JButton bingo;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel lNumero;
    public javax.swing.JLabel lTempo;
    // End of variables declaration//GEN-END:variables
}
